import turtle as t

t.shape("turtle")
t.color("blue")
t.pensize(4)
t.speed(5)

def zero():
    t.pendown()
    t.forward(35)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.forward(35)
    t.left(90)
    t.forward(70)
    t.left(90)
    t.penup()
    t.forward(50) 

def one():
    t.penup()
    t.left(90)
    t.forward(35)
    t.right(45)
    t.pendown()
    t.forward(50)
    t.right(135)
    t.forward(70)
    t.left(90)
    t.penup()
    t.forward(15)    

def two():
    t.forward(35)
    t.right(180)
    t.pendown()
    t.forward(35)
    t.right(135)
    t.forward(50)
    t.left(45)
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.left(90)
    t.penup()
    t.forward(70)
    t.left(90)
    t.forward(50)

def three():
    t.pendown()
    t.left(45)
    t.forward(50)
    t.left(135)
    t.forward(35)
    t.right(135)
    t.forward(50)
    t.left(135)
    t.forward(35)
    t.left(90)
    t.penup()
    t.forward(70)
    t.left(90)
    t.forward(50)

def four():
    t.penup()
    t.forward(35)
    t.left(90)
    t.pendown()
    t.forward(70)
    t.backward(35)
    t.left(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.penup()
    t.backward(70)
    t.right(90)
    t.forward(50)

def five():
    t.pendown()
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.penup()
    t.forward(70)
    t.left(90)
    t.forward(15)

def six():
    t.left(90)
    t.forward(35)
    t.left(180)
    t.pendown()
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.right(135)
    t.forward(50)
    t.right(135)
    t.penup()
    t.forward(70)
    t.left(90)
    t.forward(15)

def seven():
    t.pendown()
    t.left(90)
    t.forward(35)
    t.right(45)
    t.forward(50)
    t.left(135)
    t.forward(35)
    t.penup()
    t.left(90)
    t.forward(70)
    t.left(90)
    t.forward(50)

def eight():
    t.forward(35)
    t.pendown()
    t.backward(35)
    t.left(90)
    t.forward(75)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.backward(35)
    t.left(90)
    t.forward(35)
    t.penup()
    t.left(90)
    t.forward(15)

def nine():
    t.pendown()
    t.left(45)
    t.forward(50)
    t.left(135)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.penup()
    t.forward(35)
    t.left(90)
    t.forward(15)
            
def post_index():
    A={ 1:"one()", 2:"two()", 3:"three()",4:"four()",
             5:"five()", 6:"six()",7:"seven()", 8:"eight()",
             9:"nine()", 0:"zero()",}
    B = list(map(int, input("Post index:")))
    for i in B:
       eval(A[i])

post_index()
   
